rules:
  master:
    level: failure
    message: >
      Please consider an alternative to `primary`.

      See  https://inclusivenaming.org/ for more information
  slave:
    level: failure
    message: >
      Please consider an alternative to `secondary`. 
      
      See  https://inclusivenaming.org/ for more information
  foo:
    regex:
      - /foo/gi
      - /foobar/gi
      - /foos/gi
    level: failure
ignore:
 - ".github/in-solidarity.yml"  # default
 - "**/*.yml"
